#  Copyright 2024 The Fluid Authors.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

{{- if .Values.master.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cachefs.fullname" . }}-master-svc
  labels:
    app: {{ template "cachefs.name" . }}
    chart: {{ template "cachefs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: cachefs-master-svc
  {{- if .Values.owner.enabled }}
  ownerReferences:
  - apiVersion: {{ .Values.owner.apiVersion }}
    blockOwnerDeletion: {{ .Values.owner.blockOwnerDeletion }}
    controller: {{ .Values.owner.controller }}
    kind: {{ .Values.owner.kind }}
    name: {{ .Values.owner.name }}
    uid: {{ .Values.owner.uid }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "cachefs.name" . }}
    chart: {{ template "cachefs.chart" . }}
    release: {{ .Release.Name }}
    role: cachefs-master
  ports:
    - name: master-port
      port: {{ .Values.master.port }}
      protocol: TCP
{{- end }}
