apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-data-load-script" .Release.Name }}
  labels:
    release: {{ .Release.Name }}
    role: dataload-job
data:
  dataloader.distributedLoad: |
    #!/usr/bin/env bash
    set -xe

    function main() {
        paths="$DATA_PATH"
        paths=(${paths// / })

        targetPath=""
        for((j=0;j<${#paths[@]};j++)) do
          targetPath="$targetPath $MOUNTPATH${paths[j]}"
        done

        podNames="$POD_NAMES"
        podNames=(${podNames//:/ })

        ns="$POD_NAMESPACE"

        checkPathResult=$(/usr/local/bin/kubectl -n $ns exec -it "${podNames[0]}" -- timeout 30s /bin/ls $targetPath |& head -3)
        strUnexistence="No such file or directory"
        if [[ $checkPathResult =~ $strUnexistence ]]; then
            echo -e "dataLoad failed because some paths not exist."
            exit 1
        fi

        echo -e "cachefs warmup $targetPath starts"
        local pod="${podNames[0]}"
        /usr/local/bin/kubectl -n $ns exec -it $pod -- timeout $TIMEOUT /bin/cachefs warmup $targetPath
        echo -e "cachefs warmup $targetPath ends"
    }
    main "$@"
